# Generated by Django 5.0 on 2023-12-11 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moominmugs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moominmug',
            name='color',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moominmug',
            name='figure',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moominmug',
            name='theme',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='moominmug',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
