# Generated by Django 5.0 on 2023-12-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moominmugs', '0004_moominmug_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moominmug',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='moominmug',
            name='figure',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='moominmug',
            name='officialName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='moominmug',
            name='theme',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
