# Generated by Django 5.0 on 2023-12-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moominmugs', '0005_alter_moominmug_color_alter_moominmug_figure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moominmug',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
