# Generated by Django 5.0 on 2023-12-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moominmugs', '0006_alter_moominmug_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moominmug',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
